//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Standard.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTest
    {
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public string UserID { get; set; }
        public string UserID_text { get; set; }
        public string DeptID { get; set; }
        public string DeptName { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public string Type { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> WriteTime { get; set; }
        public Nullable<double> Days { get; set; }
        public string test { get; set; }
        public string test1 { get; set; }
        public string test2 { get; set; }
        public string test2_text { get; set; }
        public Nullable<int> flowcompleted { get; set; }
    }
}
