//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Standard.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTest_WorkOrder
    {
        public int ID { get; set; }
        public string Client_Number { get; set; }
        public string Client_Name { get; set; }
        public string Client_Phone { get; set; }
        public string Client_Tel { get; set; }
        public string Client_Company { get; set; }
        public string Client_CarNumber { get; set; }
        public string Client_CarJH { get; set; }
        public string Disp_Number { get; set; }
        public string Disp_Urgency { get; set; }
        public string Disp_SubmitUser { get; set; }
        public string Disp_HelpModel { get; set; }
        public string Disp_SelectModel { get; set; }
        public string Disp_Jdd { get; set; }
        public Nullable<System.DateTime> Disp_Time { get; set; }
        public string Disp_Bc { get; set; }
        public string Disp_Engineer { get; set; }
        public string Disp_EngineerPhone { get; set; }
        public string Disp_CarNumber { get; set; }
        public string Disp_Type { get; set; }
        public string Disp_BussType { get; set; }
        public string Disp_Completed { get; set; }
        public string Disp_Address { get; set; }
    }
}
