//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Standard.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInfo
    {
        public System.Guid UserID { get; set; }
        public string Tel { get; set; }
        public string Phone { get; set; }
        public string OtherTel { get; set; }
        public string Fax { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public string Note { get; set; }
    }
}
