//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Standard.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowDelegation
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<System.Guid> FlowID { get; set; }
        public System.Guid ToUserID { get; set; }
        public System.DateTime WriteTime { get; set; }
        public string Note { get; set; }
    }
}
