//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Standard.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlow
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public System.Guid Type { get; set; }
        public string Manager { get; set; }
        public string InstanceManager { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid CreateUserID { get; set; }
        public string DesignJSON { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<System.Guid> InstallUserID { get; set; }
        public string RunJSON { get; set; }
        public int Status { get; set; }
    }
}
