//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Standard.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowTask
    {
        public System.Guid ID { get; set; }
        public System.Guid PrevID { get; set; }
        public System.Guid PrevStepID { get; set; }
        public System.Guid FlowID { get; set; }
        public System.Guid StepID { get; set; }
        public string StepName { get; set; }
        public string InstanceID { get; set; }
        public System.Guid GroupID { get; set; }
        public int Type { get; set; }
        public string Title { get; set; }
        public System.Guid SenderID { get; set; }
        public string SenderName { get; set; }
        public System.DateTime SenderTime { get; set; }
        public System.Guid ReceiveID { get; set; }
        public string ReceiveName { get; set; }
        public System.DateTime ReceiveTime { get; set; }
        public Nullable<System.DateTime> OpenTime { get; set; }
        public Nullable<System.DateTime> CompletedTime { get; set; }
        public Nullable<System.DateTime> CompletedTime1 { get; set; }
        public string Comment { get; set; }
        public Nullable<int> IsSign { get; set; }
        public int Status { get; set; }
        public string Note { get; set; }
        public int Sort { get; set; }
        public Nullable<System.Guid> SubFlowGroupID { get; set; }
    }
}
